### ISSUE TITLE
change master to main in ci.yml

### ISSUE THREAD

**Issue by RoryWirch** [RoryWirch/KojiChannelValidator#52]
In ci.yml pytest is set to run on pushes and pull requests to the master branch. Github changed the terminology master to main, so ci.yml does not run.

**Comment by gabriellasroman** [comment]
update: "master" has been changed to "main" -> ci.yml runs but fails

**Comment by gabriellasroman** [comment]
update: ci.yml runs when "master" is changed to "main" but fails -- working on resolving failure
