### ISSUE TITLE
Remaining PyPi Publishing setup

### ISSUE THREAD

**Issue by gabriellasroman** [RoryWirch/KojiChannelValidator#84]
- setup.py
  - determine minimum python version required
  - verify install_requires
- move koji_channel_validator into src --> src/koji_channel_validator/
- generate distribution archives
- determine if TOML file is needed (or is requirements.txt sufficient?)
- - README.md
  - add mentors?

**Comment by RoryWirch** [comment]
I'm closing this issue as the tool has been published to PyPi here: https://pypi.org/project/KojiChannelValidator/
I have added a new issue #88 which includes updates to docs and PyPi description, which was somewhat included in this issue.
